### PR TITLE
Fix create topic failure for non-partitioned topic

### LINKED ISSUE #495: pulsar-manager create topic get 400 response
## Description
When I try to create topic with pulsar manager, but the ui can not create it and get 400 response.
In addition, I can create topic using `./bin/pulsar-admin` command line.
Please supply related solution, thank you.

## Version
* Pulsar: 2.10.2
* Pulsar Manager: 0.3.0 (Deploy from bin package)
* Instance: AWS EC2

## Image
image1
image2
image3

### PR DESCRIPTION
**Pull request by Apurva007**
Fixes #495 

### Motivation

Creating non-partitioned topics causes a HTTP 400 error. The reason is that the Pulsar admin API for non-partitioned topics only supports a metadata map. But pulsar manager defaults to sending an integer(which would be as per partitioned topic creation API) causing the error

[Non-partitioned topic creation API](https://pulsar.apache.org/admin-rest-api/#operation/createNonPartitionedTopic)
[Partitioned topic creation API](https://pulsar.apache.org/admin-rest-api/#operation/createPartitionedTopic)

### Modifications

The modification is to detect if a partitioned or non-partitioned topic is being created and based on that deciding if the integer should be passed.

### Verifying this change
Screen Shot 2022-12-29 at 2 24 14 AM

- [ X ] Make sure that the change passes the `./gradlew build` checks.

### CODE REVIEW

**Comment by Apurva007** [comment]
@tuteng  @nodece  @rdhabalia  Please can you review this change.

**Review by nodece — APPROVED** [review]

File: front-end/src/api/topics.js [hunk 1]
```diff
@@ -82,13 +82,19 @@ export function putTopic(persistent, tenant, namespace, topic, data) {
   var url = `/${persistent}/${tenant}/${namespace}/${topic}`
   if (data > 0) {
     url += '/partitions'
+    return request({
```
Comment (nodece) [inline front-end/src/api/topics.js:85]:
```suggestion
    return putTopicByPartition(persistent, tenant, namespace, topic, data);
```

File: front-end/src/api/topics.js [hunk 2]
```diff
@@ -82,13 +82,19 @@ export function putTopic(persistent, tenant, namespace, topic, data) {
   var url = `/${persistent}/${tenant}/${namespace}/${topic}`
   if (data > 0) {
     url += '/partitions'
```
Comment (nodece) [inline front-end/src/api/topics.js:84]:
```suggestion
```

File: front-end/src/api/topics.js (hunk 1 above)
Comment (Apurva007) [reply front-end/src/api/topics.js]: @nodece Thanks for pointing it out. Made the suggested changes.

File: front-end/src/api/topics.js (hunk 2 above)
Comment (Apurva007) [reply front-end/src/api/topics.js]: @nodece Thanks for pointing it out. Made the suggested changes.

**Review by nodece — APPROVED** [review]
