### PR TITLE
fix: check for existing superuser

### LINKED ISSUE #563: `/pulsar-manager/users/superuser` can create multiple same superusers,  login throws InternalServerError
Hello 👋 

Bug report, 

Right now, you are able to PUT superuser multiple times which henceforth breaks client login as there's internal server error being thrown that there's more than 1 expected result.

Request or consideration:

I'm about 85% done with integrating Pulsar into [Aspire](https://github.com/dotnet/aspire), but I would like to provide a client next to it as a plugin.

However, this seeding of superusers is making it feel necessarily hacky.
You need to wait for container to spin up and start accepting then make request to some /superuser endpoint 

Can some defaults arrive with the config or envvars like rabbit management plugin would

### PR DESCRIPTION
**Pull request by maranmaran**
Fixes #563 and #537

### Motivation

When creating superuser, currently there's no guard to protect against already created superuser. 
If you seed superuser more then one times, it breaks login for that particular user as the request throws `InternalServerError` on login

### Modifications

In the same style of other guards within `UsersController` I've added query to repository to get entity by name for the incoming user payload. If the entity exists we return validation error.

### Verifying this change
- [x] Make sure that the change passes the `./gradlew build` checks.

### CODE REVIEW

File: src/main/java/org/apache/pulsar/manager/controller/UsersController.java [hunk 1]
```diff
@@ -218,6 +218,11 @@ public ResponseEntity<Map<String, Object>> createSuperUser(@RequestBody UserInfo
             result.put("error", "Please provider password");
             return ResponseEntity.ok(result);
         }
+        Optional<UserInfoEntity> optionalUserEntity =  usersRepository.findByUserName(userInfoEntity.getName());
+        if (optionalUserEntity.isPresent()) {
+            result.put("error", "Superuser already exists");
+            return ResponseEntity.ok(result);
```
Comment (lhotari) [inline src/main/java/org/apache/pulsar/manager/controller/UsersController.java:224]: The previous solution of using ok for errors is strange, but I guess it's fine to follow the original bad convention.

**Review by lhotari — APPROVED** [review]
LGTM

File: src/main/java/org/apache/pulsar/manager/controller/UsersController.java (hunk 1 above)
Comment (maranmaran) [reply src/main/java/org/apache/pulsar/manager/controller/UsersController.java:224]: Yes thanks for pointing it out, there's some other ❓ , but I'm trying to focus on my use-case here following as you say same convention, not really sure what else might depend on the original convention in terms of client handling

**Comment by lhotari** [comment]
Thanks for the contribution @maranmaran
