### PR TITLE
fix unload namespace error

### LINKED ISSUE #385: the primary key conflict inserted into the NameSpace database is abnormal
When the unload operation of the bundles is executed, the background keeps reporting that the primary key conflict inserted into the NameSpace database is abnormal.

### PR DESCRIPTION
**Pull request by g0715158**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #385

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #385

*Describe the modifications you've done.*

When the unload operation of the bundles is executed, the background keeps reporting that the primary key conflict inserted into the NameSpace database is abnormal.

 ase add `Fixes #<xyz>`.)*

Fixes #385

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #385

*Describe the modifications you've done.*

Perform a check for existence before the namespace is inserted, if it exists, no more insertion is performed

### CODE REVIEW

**Review by xuesongxs — APPROVED** [review]
This check should be done

File: src/main/java/org/apache/pulsar/manager/dao/NamespacesRepositoryImpl.java [hunk 1]
```diff
@@ -105,6 +105,10 @@ public void remove(String tenant, String namespace) {
 
     @Override
     public long save(NamespaceEntity namespacesEntity) {
+        NamespaceEntity entity = namespacesMapper.findByTenantNamespace(namespacesEntity.getTenant(),namespacesEntity.getNamespace());
+        if (entity!=null){
```
Comment (tuteng) [inline src/main/java/org/apache/pulsar/manager/dao/NamespacesRepositoryImpl.java:109]: Try format code:

```
if (entity != null)
```

Comment (g0715158) [reply src/main/java/org/apache/pulsar/manager/dao/NamespacesRepositoryImpl.java]: Already resolved

**Review by tuteng — APPROVED** [review]
